# Análise do dataset

In [3]:
import pandas as pd

df = pd.read_csv("./healthcare_patient_journey.csv")

display(df.head())

,patient_id,age,gender,chronic_condition,admission_type,department,wait_time_min,length_of_stay_days,procedures_count,medication_count,complications,discharge_status,readmitted_30d,total_cost_€,satisfaction_score
0,1,69,male,0,scheduled,Neurology,41,2,0,3,1,referred,1,1440,2
1,2,38,male,0,emergency,Oncology,17,3,1,2,0,recovered,0,2060,3
2,3,81,male,0,scheduled,Neurology,40,2,3,2,0,recovered,0,2110,3
3,4,67,female,1,emergency,ER,7,4,5,9,0,recovered,0,4070,3
4,5,88,male,1,emergency,Cardiology,34,3,7,5,0,recovered,1,3800,3

# Tratamento dos Dados

In [4]:
# Definindo função de separação de linhas
def linhas():
    print("-" * 20)

In [6]:
# Investigando se há alguma patologia nos dados

# Verificando campos que tem valores nulos
print(df.isnull().any())

linhas()

# Verificando se há IDs duplicados na base (que deverião ser únicos)
ids_duplicados = df['patient_id'].duplicated()
print(f"Quantidade de IDs duplicados: {ids_duplicados.sum()}")

linhas()

# Verificando se há valores não numéricos em campos numéricos
colunas_numericas = ["age", "chronic_condition", "wait_time_min", "length_of_stay_days", "procedures_count", "medication_count", "complications", "readmitted_30d", "total_cost_€", "satisfaction_score"]

for coluna in colunas_numericas:
    invalidos = pd.to_numeric(df[coluna], errors='coerce').isna()
    print(f"Coluna: {coluna} -> {invalidos.sum()} valores não numéricos")

linhas()

# Verificando se há valores negativos que podem corromper a base
for coluna in colunas_numericas:
    negativos = (df[coluna] < 0)
    print(f"Coluna: {coluna} -> {negativos.sum()} valores negativos")

linhas()

# Verificando se há valores diferentes de 0 ou 1 em campos binários
colunas_binarias = ["chronic_condition", "complications", "readmitted_30d"]

for coluna in colunas_binarias:
    invalidos = (df[coluna] != 0) & (df[coluna] != 1)
    print(f"Coluna: {coluna} -> {invalidos.sum()} valores inválidos")

linhas()

# Verificando como estão os dados no campo ´total_coast´
print(df['total_cost_€'])

linhas()

# Verificando a padronização dos campos categóricos
print(df['gender'].unique())
print(df['admission_type'].unique())
print(df['department'].unique())
print(df['discharge_status'].unique())

linhas()

# Verificando a maior e menor idade
print(df['age'].min())
print(df['age'].max())

patient_id             False
age                    False
gender                 False
chronic_condition      False
admission_type         False
department             False
wait_time_min          False
length_of_stay_days    False
procedures_count       False
medication_count       False
complications          False
discharge_status       False
readmitted_30d         False
total_cost_€           False
satisfaction_score     False
dtype: bool
--------------------
Quantidade de IDs duplicados: 0
--------------------
Coluna: age -> 0 valores não numéricos (coluna numérica)
Coluna: chronic_condition -> 0 valores não numéricos (coluna numérica)
Coluna: wait_time_min -> 0 valores não numéricos (coluna numérica)
Coluna: length_of_stay_days -> 0 valores não numéricos (coluna numérica)
Coluna: procedures_count -> 0 valores não numéricos (coluna numérica)
Coluna: medication_count -> 0 valores não numéricos (coluna numérica)
Coluna: complications -> 0 valores não numéricos (coluna numérica)
Coluna: readmitted_30d -> 0 valores não numéricos (coluna numérica)
Coluna: total_cost_€ -> 0 valores não numéricos (coluna numérica)
Coluna: satisfaction_score -> 0 valores não numéricos (coluna numérica)
--------------------
Coluna: age -> 0 valores negativos
Coluna: chronic_condition -> 0 valores negativos
Coluna: wait_time_min -> 0 valores negativos
Coluna: length_of_stay_days -> 0 valores negativos
Coluna: procedures_count -> 0 valores negativos
Coluna: medication_count -> 0 valores negativos
Coluna: complications -> 0 valores negativos
Coluna: readmitted_30d -> 0 valores negativos
Coluna: total_cost_€ -> 0 valores negativos
Coluna: satisfaction_score -> 0 valores negativos
--------------------
Coluna: chronic_condition -> 0 valores diferentes de 0 e 1 (coluna binária)
Coluna: complications -> 0 valores diferentes de 0 e 1 (coluna binária)
Coluna: readmitted_30d -> 0 valores diferentes de 0 e 1 (coluna binária)

In [ ]:
# Conversão do euro para dólar
dolar = 1.16
df['total_cost_€'] = df['total_cost_€'] * dolar

In [ ]:
# Renomeação das colunas
df.rename(columns={
    "patient_id": "id_paciente",
    "age": "idade",
    "gender": "genero",
    "chronic_condition": "condicao_cronica",
    "admission_type": "tipo_admissao",
    "department": "departamento",
    "wait_time_min": "tempo_espera_min",
    "length_of_stay_days": "duracao_estadia_dias",
    "procedures_count": "qtd_procedimentos",
    "medication_count": "qtd_medicamentos",
    "complications": "complicacoes",
    "readmitted_30d": "retorno_apos_30d",
    "total_cost_€": "custo_total_dolares",
    "satisfaction_score": "nivel_satisfacao"
}, inplace=True)

%md
# Resultado da Análise e do Tratamento de Colunas

Ao analisar as 15 colunas já vindas do dataset, percebeu-se que não havia nenhum tipo de patologia nos dados. Todos os campos estavam devidamente tratados e com seus devidos tipos:
- Todas as colunas numéricas tinham apenas dados numéricos
- Colunas binárias (de 0 ou 1) não tinham dados diferentes desses dois números
- Não haviam IDs duplicados
- Nenhum tipo de dado nulo dentre os 3000 dados presentes na base
- Não há falta de padronização dentre as colunas categóricas -> Tudo em minúsculo, com exceção do campo `departament` que foi tratado para todos os dados serem minúsculos
- Idades presentes no campo `age` entre 18 e 89 anos, que são dados coerentes e estáveis dentro da base

## Renomeação de Colunas

As colunas estavam de fácil entendimento, porém estavam em inglês, e como nosso dashboard será feito em português decidimos renomeá-las para facilitar a interpretação dos dados e tornar a visualização mais intuitiva para os usuários finais.

Segue abaixo a renomeação realizada:

- `patient_id` → `id_paciente`
- `age` → `idade`
- `gender` → `genero`
- `chronic_condition` → `condicao_cronica`
- `admission_type` → `tipo_admissao`
- `department` → `departamento`
- `wait_time_min` → `tempo_espera_min`
- `length_of_stay_days` → `duracao_estadia_dias`
- `procedures_count` → `qtd_procedimentos`
- `medication_count` → `qtd_medicamentos`
- `complications` → `complicacoes`
- `readmitted_30d` → `retorno_apos_30d`
- `total_cost_€` → `custo_total_dolares`
- `satisfaction_score` → `nivel_satisfacao`

## Conversão do Campo `custo_total_dolares`
Ao analisar a base e pensarmos na elaboração do dashboard, decidimos converter do euro para o dólar pelo fato de a moeda oficial do dashboard ser o dólar ($).

Levamos em consideração o valor do dólar no dia **22/05/2026**

1 euro (€) = 1,16 dólars americanos ($)

In [ ]:
# Subindo base para o spark
spark.createDataFrame(df).write.mode("overwrite").saveAsTable("df_healthcare_dataset")

# KPIs
- Tempo Médio de Espera p/Departamento
- Período Médio de Estadia p/Departamento
- Quantidade de Pacientes com Doenças Crônicas ✅
- Quantidade de Procedimentos p/Departamento
- Preço Médio p/Departamento✅
- Preço Médio Geral ✅
- Nível de Satisfação p/Departamento
- Nível de Satisfação p/Período de Estadia
- Nível de Satisfação Geral ✅
- Satisfação p/Gênero
- Quantidade de Pacientes p/Tipo de Admissão
- Nível de Satisfação p/Tempo de Espera
- Tempo de Espera p/Tipo de Admissão
- Preço por Satisfação (Scatter) ✅
- Quantidade de Medicamentos x Preço x Departamento ✅
- Quantidade de Medicamentos por Quantidade de Procedimentos (Scatter) ✅

In [7]:
display(df.sort_values(by="total_cost_€", ascending=False))

,patient_id,age,gender,chronic_condition,admission_type,department,wait_time_min,length_of_stay_days,procedures_count,medication_count,complications,discharge_status,readmitted_30d,total_cost_€,satisfaction_score
1379,1380,84,male,1,scheduled,ER,41,10,5,7,0,recovered,1,6610,3
2054,2055,79,female,1,emergency,Polyclinic,34,11,5,1,1,referred,0,6580,2
1253,1254,66,female,1,emergency,Neurology,12,9,6,9,0,recovered,1,6570,4
2510,2511,78,male,1,emergency,Neurology,12,7,10,6,1,referred,1,6430,2
315,316,38,female,1,scheduled,Oncology,48,9,7,4,0,recovered,0,6420,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173,2174,20,female,0,scheduled,Neurology,44,1,0,1,0,recovered,0,830,2
1351,1352,41,male,0,scheduled,Neurology,59,1,0,1,0,recovered,0,830,4
2794,2795,38,male,0,emergency,Polyclinic,34,1,0,0,0,recovered,0,750,3
1313,1314,46,female,0,emergency,Neurology,41,1,0,0,0,recovered,0,750,3
2219,2220,75,male,0,emergency,ER,34,1,0,0,0,recovered,0,750,3